import { DocumentHighlight } from 'vscode-languageclient';
import { Token } from 'antlr4ng';
import * as LexerUtil from '../util/LexerUtil';
import { GslLexer } from '../antlr/autogenerated/GslLexer';
import { handleBlockHighlight } from './handleBlockHighlight';
import { ParseResult } from '../ParsingManager';

export const handleThenHighlight = (
    tokens: Token[],
    { index }: LexerUtil.FindTokenResult,
    parseResult: ParseResult
): DocumentHighlight[] => {
    const ifStatement = LexerUtil.findPreviousToken(
        tokens,
        index - 1,
        (t) =>
            t.type === GslLexer.IF ||
            t.type === GslLexer.IFNOT ||
            t.type === GslLexer.ELSE_IF ||
            t.type === GslLexer.ELSE_IFNOT
    );
    if (!ifStatement) return [];
    // At one point this was also highlighting THEN, but it felt
    // unnecessary and loud
    return handleBlockHighlight(tokens, ifStatement, parseResult);
};
